### ISSUE TITLE
Ability to manage fishing spots (map/locations tab)

### ISSUE THREAD

**Issue by cohenadair** [cohenadair/anglers-log#178]
**Data Structure**
```
FishingSpot {
    UNIQUE LatLng coordinates
    UNIQUE OPTIONAL BodyOfWater bodyOfWater
    UNIQUE (in BoW iff BoW set; global otherwise) OPTIONAL String name
}
```
**UI**
* See notebook.
* Basically, managed via long press on Google Map + bottom sheet. See Google Maps app.
* Tooltip upon first tap of Map tab.

**Tasks**
- [x] Add Google Map to Map tab
- [x] Show marker and bottom sheet on long press of map
- [x] Add functional current location button
- [x] Style bottom sheet like Google Maps, including swipe down to close
- [x] Add content to bottom sheet for "new" fishing spot
- [x] "Save" button opens screen to add a fishing spot
- [x] Fishing spots added to database
- [x] "Not-yet-added" pins rendered differently, removed if not saved
- [x] Add content to bottom sheet for "selected" fishing spot
- [x] Allow editing of selected fishing spots
- [x] Add search bar to map
- [x] Allow deleting of fishing spots
- [x] Add animations
- [x] Add map type button
- [x] Add custom "my location" button (built in on is covered by bottom sheet)
