### ISSUE TITLE
(UR: 1) Generalized time-of-day selection for catches

### ISSUE THREAD

**Issue by cohenadair** [cohenadair/anglers-log#196]
A user requested for the addition of time-of-day selections when adding catches, such as dusk, night, and dawn.  This would be a simple addition to catches and implemented using a [picker](https://developer.apple.com/ios/human-interface-guidelines/ui-controls/pickers/) on iOS, and a [Spinner](https://developer.android.com/guide/topics/ui/controls/spinner.html) or [radio button dialog](https://developer.android.com/guide/topics/ui/dialogs.html) on Android.

**Time of day options**
* Dawn
* Morning
* Afternoon
* Dusk
* Night

**Tasks**
- [ ] Implement a `generalizedTimeOfDay` property to the `Catch` object
- [ ] Add UI element for selection to the add catch screen
- [ ] Implement backup and restore for the new property
- [ ] Automatic calculation of the `generalizedTimeOfDay` property based on the catch's wall time. This might involve some location data to find out when dawn/dusk was for the current day.

**Comment by cohenadair** [comment]
Will be done with #387.
