### ISSUE TITLE
(UR: 1) Fishing spot property enhancements

### ISSUE THREAD

**Issue by cohenadair** [cohenadair/anglers-log#371]
Additions:
- [x] User request -- Photo(s) (#199)
- [x] User request -- Notes (#289)
- [x] ~Manual coordinates (#282)~ Wasn't user requested, so there's no need.
- [x] ~Name should not be required (#234)~ Done previously.
- [x] Body of water -- works like bait categories: fishing spot has an associated body of water
- [x] ~Allow re-picking of coordinates~ Descoped.
- [x] Fishing spot list should include bodies of water section headers
- [x] Tapping fishing spot photo should open full screen page
