### ISSUE TITLE
Catch property enhancements

### ISSUE THREAD

**Issue by cohenadair** [cohenadair/anglers-log#387]
Add all properties from data_structure.md doc that are not already included.

Duplicate issues/requests:
Some of these can be added as "custom fields". Will need to review each one individually.
- [x] #287 - Decimal water temperature
- [x]  ~Add "Water Speed" to catches #251 / Add "water flow" to Catch #450~ Can be added via custom field
- [x]  Better units selection #77 / Allow decimal imperial weights #327
- [x]  Generalized time-of-day selection for catches #196
- [x]  ~Add to Catch: Tournament vs. Recreational #307~ Can be added via custom field

**Comment by cohenadair** [comment]
Should revisit old issues and remove less-requested features from 2.0 and mark as a future enhancement.

**Comment by cohenadair** [comment]
The rest was finished in 83d61dec7cc08ffc592570b081d845bfebf5a5fb.
