### ISSUE TITLE
Release testing checklist

### ISSUE THREAD

**Issue by cohenadair** [cohenadair/anglers-log#505]
Test cases that can't be fully automated:

**Either Platform**
- [x] Pro features listed on `ProPage` are only available when pro
- [x] Custom fields and reports are covered after subscription ends
- [x] Brand new user onboarding
- [x] Locales - US, Canada, UK, AUS

**iOS**
- [x] In-app purchase
- [x] Migrating from 1.X
- [x] Backup and restore
- [x] Google auth on release builds
- [x] Ads are served
- [x] Subscription renewals are applied in app

**Android**
- [x] In-app purchase
- [x] Migrating from 1.X
- [x] Backup and restore
- [x] Google auth on release builds (for Android, may need to [setup SHA](https://stackoverflow.com/questions/54557479/flutter-and-google-sign-in-plugin-platformexceptionsign-in-failed-com-google) keys)
- [x] Ads are served
- [x] Subscription renewals are applied in app
