### ISSUE TITLE
2.7.0 release testing checklist

### ISSUE THREAD

**Issue by cohenadair** [cohenadair/anglers-log#892]
Area's to test:
- [x] Android permissions
- [x] Photo access and file picking (Android)
- [x] Photo access and file picking (iOS)
- [x] GPS trail map/fishing spot map zoom is correct (#797 reopened)
- [x] Subscriptions (Android)
- [x] Subscriptions (iOS)
- [x] Verify start/end timestamp fields are shown for trips (new user)
- [x] Tide chart axes
- [x] Tide fetching
- [x] Tide manual input (Created #916)
- [x] Filter catches by tide
- [x] Send feedback on real iPhone with Safari only
- [x] Local notifications for failed auto-backups; test scenarios in #769 (iOS)
- [x] Local notifications for failed auto-backups (Android) (#769 reopened)
- [x] Photo bait variants (bait list thumb, bait page, save bait page, variant page, save variant page)
- [x] Updating app from non-empty bait variant preference fields still shows photo field
- [x] Updating app from non-empty trip preference fields still shows water fields
- [x] Add/edit water on trips
- [x] View water on trips
- [x] Filter trips by water
- [x] Skip fishing spot selection in catch journey
- [x] Remove fishing spot from catch
- [x] Copy catch (free)
- [x] Copy catch (pro)
- [x] iPad CSV export
- [x] iPad share trip and catch
- [x] Species counter (free)
- [x] Species counter (pro)
  - [x] #917
  - [x] #918
- [x] "Blanked" for skunked trips (UK locale)
